/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/planet.glb -t 
*/

"use client"
import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type ActionName = 'actionNameOne' | 'actionNameTwo';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

interface MyGLTFResult extends GLTFResult {
  animations: GLTFAction[];
}

type GLTFResult = GLTF & {
  nodes: {
    Icosphere: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Planet(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('./models/planet.glb') as GLTFResult

  const ref = useRef<THREE.Group<THREE.Object3DEventMap>>(null!)

  // useFrame(({clock}) => {
  //   ref.current.rotation.x = Math.sin(clock.getElapsedTime())
  // })

  // useFrame(({ clock }) => {
  //   ref.current.rotation.x = clock.getElapsedTime()
  // })


  useFrame((state, delta) => (ref.current.rotation.x += delta))
  
  return (
    <group {...props} dispose={null} ref={ref} >
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.001']} rotation={[0, -1.516, 0]} />
    </group>
  )
}

useGLTF.preload('./models/planet.glb')
