/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/planet.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import gsap from "gsap"
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const FLOOR_HEIGHT = 2.3
const NB_FLOORS = 3

export function Planet(props) {
  const { nodes, materials } = useGLTF('./models/planet.glb')
  const ref = useRef()
  const tl = useRef()

  // const scroll = useScroll()

  // useFrame(() => {
  //   tl.current.seek(scroll.offset * tl.current.duration())
  // })

  useFrame(({clock}) => {
    ref.current.rotation.x = Math.sin(clock.getElapsedTime())
  })

  useLayoutEffect(() => {
    
    // tl.current = gsap.timeline()

    // tl.current.to(
    //   ref.current.position, 
    //   {
    //     duration: 2,
    //     y: -FLOOR_HEIGHT * (NB_FLOORS - 1)
    //   },
    //   0
    // )
  }, [])

  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.001']} rotation={[0, -1.516, 0]} />
    </group>
  )
}

useGLTF.preload('./models/planet.glb')
